[gitlab]
gitlab01 ansible_host=10.10.0.130

[jenkins_controller]
jenkins01 ansible_host=10.10.0.131

[jenkins_agents]
build01 ansible_host=10.10.0.132

[k3s_servers]
k3s01 ansible_host=10.10.0.133
k3s02 ansible_host=10.10.0.134
k3s03 ansible_host=10.10.0.135

[cicd_lab:children]
gitlab
jenkins_controller
jenkins_agents
k3s_servers

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
ansible_private_key_file=/home/root/.ssh/AnsibleVM